# This is a basic workflow to help you get started with Actions

name: Deploy to ec2

# Controls when the action will run. 
on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  workflow_dispatch:

jobs:
  build:
  # 어떤 OS 환경에서 실행할지 지정하는 runs-on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
